apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-fiwrkhco
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-fiwrkhco:821b5ca34a461c3d00814ef274e55d4613aa9bdc@sha256:6561bf1f731094161fdfbc91c3c71950400cedce9b9efbef272c800f32e88872
        name: container-image  
